"use client"

import { useState } from "react"
import { useAuth } from "@/lib/auth-context"
import { API_BASE_URL } from "@/lib/config"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Switch } from "@/components/ui/switch"
import { Separator } from "@/components/ui/separator"
import { Alert, AlertDescription } from "@/components/ui/alert"

interface TotpSetupPayload {
  qrCodeSvg?: string
  qrCodePngBase64?: string
  manualKey?: string
  sharedKey?: string
  otpauthUrl?: string
}

export default function SettingsPage() {
  const { user, token, refreshUser } = useAuth()
  const [isSaving, setIsSaving] = useState(false)
  const [totpSetup, setTotpSetup] = useState<TotpSetupPayload | null>(null)
  const [totpCode, setTotpCode] = useState("")
  const [totpError, setTotpError] = useState("")
  const [totpSuccess, setTotpSuccess] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [isVerifying, setIsVerifying] = useState(false)
  const [isDisabling, setIsDisabling] = useState(false)

  const handleSave = async () => {
    setIsSaving(true)
    await new Promise((resolve) => setTimeout(resolve, 1000))
    setIsSaving(false)
  }

  const handleStartTotpSetup = async () => {
    if (!token) {
      setTotpError("You must be signed in to manage two-factor authentication.")
      return
    }

    setTotpError("")
    setTotpSuccess("")
    setIsGenerating(true)

    try {
      const res = await fetch(`${API_BASE_URL}/api/auth/totp/setup`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      })

      if (!res.ok) {
        const body = await res.json().catch(() => null)
        const message = body?.message ?? "Unable to generate authenticator setup."
        throw new Error(message)
      }

      const data = (await res.json()) as TotpSetupPayload
      setTotpSetup(data)
      setTotpCode("")
    } catch (error) {
      setTotpError(error instanceof Error ? error.message : "Unable to start setup")
    } finally {
      setIsGenerating(false)
    }
  }

  const handleConfirmTotp = async () => {
    if (!token) {
      setTotpError("You must be signed in to verify your authenticator setup.")
      return
    }

    if (!totpCode || totpCode.length < 6) {
      setTotpError("Enter the 6-digit code generated by your authenticator app.")
      return
    }

    setTotpError("")
    setTotpSuccess("")
    setIsVerifying(true)

    try {
      const res = await fetch(`${API_BASE_URL}/api/auth/totp/enable`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ code: totpCode }),
      })

      if (!res.ok) {
        const body = await res.json().catch(() => null)
        const message = body?.message ?? "Verification failed. Check the code and try again."
        throw new Error(message)
      }

      await refreshUser()
      setTotpSuccess("Two-factor authentication is now enabled on your account.")
      setTotpSetup(null)
      setTotpCode("")
    } catch (error) {
      setTotpError(error instanceof Error ? error.message : "Unable to enable two-factor authentication")
    } finally {
      setIsVerifying(false)
    }
  }

  const handleDisableTotp = async () => {
    if (!token) {
      setTotpError("You must be signed in to update your security settings.")
      return
    }

    setTotpError("")
    setTotpSuccess("")
    setIsDisabling(true)

    try {
      const res = await fetch(`${API_BASE_URL}/api/auth/totp`, {
        method: "DELETE",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      })

      if (!res.ok) {
        const body = await res.json().catch(() => null)
        const message = body?.message ?? "Unable to disable two-factor authentication."
        throw new Error(message)
      }

      await refreshUser()
      setTotpSuccess("Two-factor authentication has been disabled.")
      setTotpSetup(null)
      setTotpCode("")
    } catch (error) {
      setTotpError(error instanceof Error ? error.message : "Unable to disable two-factor authentication")
    } finally {
      setIsDisabling(false)
    }
  }

  const renderQrCode = () => {
    if (!totpSetup) return null

    if (totpSetup.qrCodeSvg) {
      return <div dangerouslySetInnerHTML={{ __html: totpSetup.qrCodeSvg }} className="[&>svg]:h-48 [&>svg]:w-48" />
    }

    if (totpSetup.qrCodePngBase64) {
      return (
        <img
          src={`data:image/png;base64,${totpSetup.qrCodePngBase64}`}
          alt="Authenticator QR code"
          className="h-48 w-48"
        />
      )
    }

    if (totpSetup.otpauthUrl) {
      return (
        <div className="rounded-lg border bg-muted p-3 text-sm break-all">
          {totpSetup.otpauthUrl}
        </div>
      )
    }

    return null
  }

  if (!user) return null

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-3xl font-bold tracking-tight">Settings</h2>
        <p className="text-muted-foreground">Manage your account settings and preferences</p>
      </div>

      <div className="grid gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Profile information</CardTitle>
            <CardDescription>Update your personal information</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid gap-2">
              <Label htmlFor="name">Full name</Label>
              <Input id="name" defaultValue={user.name} />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" type="email" defaultValue={user.email} />
            </div>
            <Button onClick={handleSave} disabled={isSaving}>
              {isSaving ? "Saving..." : "Save changes"}
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Notifications</CardTitle>
            <CardDescription>Configure how you receive notifications</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <Label>Email notifications</Label>
                <p className="text-sm text-muted-foreground">Receive notifications via email</p>
              </div>
              <Switch defaultChecked />
            </div>
            <Separator />
            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <Label>Marketing emails</Label>
                <p className="text-sm text-muted-foreground">Receive updates about new features</p>
              </div>
              <Switch />
            </div>
            <Separator />
            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <Label>Security alerts</Label>
                <p className="text-sm text-muted-foreground">Get notified about security updates</p>
              </div>
              <Switch defaultChecked />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Two-factor authentication</CardTitle>
            <CardDescription>
              Add an extra layer of protection to your account using Google Authenticator or any TOTP-compatible app.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {totpError && (
              <Alert variant="destructive">
                <AlertDescription>{totpError}</AlertDescription>
              </Alert>
            )}
            {totpSuccess && (
              <Alert>
                <AlertDescription>{totpSuccess}</AlertDescription>
              </Alert>
            )}

            {user.hasTwoFactorEnabled ? (
              <div className="space-y-4">
                <p className="text-sm text-muted-foreground">
                  Two-factor authentication is currently <span className="text-green-600 font-medium">enabled</span>.
                </p>
                <Button variant="outline" onClick={handleDisableTotp} disabled={isDisabling}>
                  {isDisabling ? "Disabling..." : "Disable two-factor authentication"}
                </Button>
              </div>
            ) : (
              <div className="space-y-4">
                <p className="text-sm text-muted-foreground">
                  Secure your account by pairing it with an authenticator app. Scan the QR code or enter the setup key, then
                  confirm the 6-digit code shown in the app.
                </p>
                {!totpSetup ? (
                  <Button onClick={handleStartTotpSetup} disabled={isGenerating}>
                    {isGenerating ? "Generating..." : "Set up two-factor authentication"}
                  </Button>
                ) : (
                  <div className="space-y-4">
                    <div className="flex flex-col items-center gap-4 rounded-lg border bg-muted/30 p-4">
                      {renderQrCode()}
                      <div className="text-sm text-muted-foreground text-center space-y-1">
                        <p className="font-medium text-foreground">Manual setup key</p>
                        <p className="font-mono text-base">{totpSetup.manualKey ?? totpSetup.sharedKey ?? "Unavailable"}</p>
                        <p>Enter this key in your authenticator app if you can&apos;t scan the QR code.</p>
                      </div>
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="totp-code">Verification code</Label>
                      <Input
                        id="totp-code"
                        inputMode="numeric"
                        pattern="\d*"
                        maxLength={6}
                        placeholder="000000"
                        value={totpCode}
                        onChange={(e) => setTotpCode(e.target.value.replace(/[^0-9]/g, ""))}
                        disabled={isVerifying}
                      />
                    </div>
                    <div className="flex flex-wrap gap-2">
                      <Button onClick={handleConfirmTotp} disabled={isVerifying}>
                        {isVerifying ? "Verifying..." : "Confirm setup"}
                      </Button>
                      <Button
                        type="button"
                        variant="ghost"
                        onClick={() => {
                          setTotpSetup(null)
                          setTotpCode("")
                        }}
                        disabled={isVerifying}
                      >
                        Start over
                      </Button>
                    </div>
                  </div>
                )}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
